apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: hashicorp/http-echo:0.2.3
          args:
            - "-text=Hello from Kubernetes Adde 🚀"
          ports:
            - containerPort: 5678

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: infra
spec:
  selector:
    app: hello-world
  ports:
    - port: 80
      targetPort: 5678
  type: ClusterIP
